version: 2
jobs:
  test:
    docker:
      - image: cimg/node:15.6
    steps:
      - checkout
      - run: npm install
      - run: npm test
  release:
    docker:
      - image: cimg/node:15.6
    steps:
      - checkout
      - run: echo release
workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
