version: 2
jobs:
  test:
    docker:
      - image: cimg/node:15.6
    steps:
      - checkout
      - run: npm install
      - run: npm test
  publish:
    docker:
      - image: cimg/node:15.6
    steps:
      - checkout
      - run: echo publish 
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
