name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: ryanwholey/conventional-changelog-action@rw-fix-uncaught-error
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
